global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "rebalancer"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          asset: "usd1"
      - targets: ["host.docker.internal:8081"]
        labels:
          asset: "usdc"
      - targets: ["host.docker.internal:8082"]
        labels:
          asset: "usdg"
      - targets: ["host.docker.internal:8083"]
        labels:
          asset: "usds"
      - targets: ["host.docker.internal:8084"]
        labels:
          asset: "usdt"
